const express=require("express"),http=require("http"),{Server}=require("socket.io"),path=require("path");
const app=express(),server=http.createServer(app),io=new Server(server);app.use(express.static(path.join(__dirname,"public")));const rooms={};
const code=()=>Math.random().toString(36).slice(2,6).toUpperCase();
const pools={money:["💎","🍀","🎲","🎯","🔥","⭐","👑","🚀","🎁","🏆","🍔","🎵","🎬","🐶","🌴","⚡","🎮","🎤","🪩","🍿","🦋","🌈","🏀","⚽","🎨","❤️","😎","🥳","🌟","🧠","🕶️"],food:["🍔","🍟","🍕","🌮","🍩","🍓","🍉","🍪","🍿","🥨","🧁","🍦","🥞","🥑","🍒","🥝","🍇","🍎"],emojis:["😂","😍","😎","🤩","🥳","😜","🤯","😭","😡","🤔","😴","🤑","🤠","🥰","😈","🤓","🙃","😇"],animals:["🐶","🐱","🦁","🐯","🐼","🐵","🦊","🐸","🐨","🐰","🦄","🐷","🐮","🐙","🦋","🐢","🦜","🐬"],music:["🎵","🎧","🎤","🎹","🥁","🎷","🎺","🎸","🪩","📻","🎼","🎶","🕺","💿","🔊","🎻","🪕","🎚️"],movies:["FRIDAY","COMING TO AMERICA","LOVE & BASKETBALL","THE WOOD","DREAMGIRLS","THE COLOR PURPLE","BLACK PANTHER","HOUSE PARTY","SOUL FOOD","BOOMERANG","THE BEST MAN","SET IT OFF","WAITING TO EXHALE","COOLEY HIGH","LEAN ON ME","JUICE","ATL","CREED"],slang:["BET","CAP","FIRE","VIBE","GOAT","TEA","SALTY","FLEX","SLAY","LIT","MOOD","DRIP","EXTRA","LOWKEY","HIGHKEY","ATE","PERIOD","SIS"],culture:["✊🏾","👑","🪮","🎤","🎶","📚","🎨","💃🏾","🕺🏾","🥁","🎓","💈","🍽️","🏆","❤️","✨","🖤","🤎"],inspiration:["FAITH","HOPE","LOVE","GRACE","JOY","PEACE","DREAM","GROW","SHINE","RISE","FOCUS","BELIEVE","PURPOSE","COURAGE","CREATE","THRIVE","BLOOM","WIN"],colors:["COLOR:#ef4444|RED","COLOR:#f97316|ORANGE","COLOR:#facc15|YELLOW","COLOR:#22c55e|GREEN","COLOR:#3b82f6|BLUE","COLOR:#a855f7|PURPLE","COLOR:#92400e|BROWN","COLOR:#111827|BLACK","COLOR:#f8fafc|WHITE","COLOR:#ec4899|PINK","COLOR:#06b6d4|CYAN","COLOR:#84cc16|LIME","COLOR:#14b8a6|TEAL","COLOR:#6366f1|INDIGO","COLOR:#f43f5e|ROSE","COLOR:#d946ef|MAGENTA","COLOR:#64748b|SLATE","COLOR:#f59e0b|GOLD"]};
function sh(a){a=[...a];for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function deck(cat,n){if(cat==="money"){let a=sh(pools.money).slice(0,31).map((v,i)=>({id:"m"+i,pair:-1,value:v,matched:false,money:false}));a.push({id:"money",pair:999,value:"$$",matched:false,money:true});return sh(a)}let v=sh(pools[cat]||pools.emojis).slice(0,n/2);return sh(v.flatMap((x,i)=>[{id:i+"a",pair:i,value:x,matched:false},{id:i+"b",pair:i,value:x,matched:false}]))}
function pub(r){return {...r,mediaReady:undefined,players:r.players.map(p=>({...p})),deck:r.deck.map(c=>({...c,value:(c.matched||r.status==="preview")?c.value:null}))}}
function emit(r){io.to(r.code).emit("state",pub(r))}
function finish(r){r.status="finished";r.elapsedSeconds=Math.max(0,Math.floor((Date.now()-(r.startedAt||Date.now()))/1000));r.winner=[...r.players].sort((a,b)=>b.score-a.score)[0]||null;emit(r)}
io.on("connection",s=>{
 s.on("create",(o,cb)=>{let c;do c=code();while(rooms[c]);let n=o.category==="money"?32:Math.max(8,Math.min(36,+o.count||16));if(n%2)n++;let r=rooms[c]={code:c,host:s.id,mode:o.mode||"classic",category:o.category||"food",count:n,status:"lobby",turn:0,players:[{id:s.id,name:String(o.name||"Host").slice(0,24),score:0}],deck:[],winner:null,previewUntil:0,startedAt:0,elapsedSeconds:0,mediaReady:new Set()};s.join(c);cb({ok:true,code:c});emit(r)});
 s.on("join",(o,cb)=>{let c=String(o.code||"").trim().toUpperCase(),r=rooms[c];if(!r)return cb({ok:false,msg:"Room not found. Check the code and try again."});if(r.status!=="lobby")return cb({ok:false,msg:"That game has already started."});if(!r.players.some(p=>p.id===s.id))r.players.push({id:s.id,name:String(o.name||"Player").slice(0,24),score:0});s.join(c);cb({ok:true,code:c,mode:r.mode,category:r.category,count:r.count});emit(r)});
 s.on("start",c=>{let r=rooms[c];if(!r||r.host!==s.id)return;r.deck=deck(r.category,r.count);r.players.forEach(p=>p.score=0);r.turn=0;r.winner=null;r.startedAt=Date.now();r.elapsedSeconds=0;if(r.mode==="flash"){let ms=Math.min(15000,4000+r.count*250);r.status="preview";r.previewUntil=Date.now()+ms;emit(r);setTimeout(()=>{if(rooms[c]===r&&r.status==="preview"){r.status="playing";emit(r)}},ms)}else{r.status="playing";emit(r)}});
 s.on("flip",(o,cb)=>{let r=rooms[o.code];if(!r||r.status!=="playing")return cb&&cb({ok:false});let pi=r.players.findIndex(p=>p.id===s.id);if(pi<0||(r.mode==="turn"&&pi!==r.turn))return cb&&cb({ok:false,msg:"Not your turn"});let c=r.deck.find(x=>x.id===o.id);if(!c||c.matched)return cb&&cb({ok:false});cb&&cb({ok:true,value:c.value,pair:c.pair,money:!!c.money})});
 s.on("pair",(o,cb)=>{let r=rooms[o.code];if(!r||r.status!=="playing")return;let a=r.deck.find(x=>x.id===o.ids?.[0]),b=r.deck.find(x=>x.id===o.ids?.[1]),p=r.players.find(x=>x.id===s.id);if(!a||!b||!p||a.matched||b.matched)return;if(a.pair===b.pair){a.matched=b.matched=true;p.score++;cb&&cb({match:true});if(r.deck.every(x=>x.matched))return finish(r);emit(r)}else{if(r.mode==="turn")r.turn=(r.turn+1)%r.players.length;cb&&cb({match:false});emit(r)}});
 // Reliable small-room WebRTC signaling: only an already-ready peer initiates to the newly-ready peer.
 s.on("media-ready",o=>{let r=rooms[o.code];if(!r||!r.players.some(p=>p.id===s.id))return;for(const id of r.mediaReady){if(id!==s.id)io.to(id).emit("media-peer",{id:s.id})}r.mediaReady.add(s.id)});
 s.on("webrtc-offer",o=>{let r=rooms[o.code];if(r&&r.players.some(p=>p.id===s.id)&&r.players.some(p=>p.id===o.to))io.to(o.to).emit("webrtc-offer",{from:s.id,description:o.description})});
 s.on("webrtc-answer",o=>{let r=rooms[o.code];if(r)io.to(o.to).emit("webrtc-answer",{from:s.id,description:o.description})});
 s.on("webrtc-ice",o=>{let r=rooms[o.code];if(r)io.to(o.to).emit("webrtc-ice",{from:s.id,candidate:o.candidate})});
 s.on("disconnect",()=>{Object.keys(rooms).forEach(c=>{let r=rooms[c],i=r.players.findIndex(p=>p.id===s.id);if(i<0)return;r.mediaReady.delete(s.id);s.to(c).emit("media-left",{id:s.id});r.players.splice(i,1);if(!r.players.length)return delete rooms[c];if(r.host===s.id)r.host=r.players[0].id;if(r.turn>=r.players.length)r.turn=0;emit(r)})})
});
server.listen(process.env.PORT||3000,()=>console.log("SWIS Memory Match v6 running"));
