const express=require("express"),http=require("http"),{Server}=require("socket.io"),path=require("path");
const app=express(),server=http.createServer(app),io=new Server(server);app.use(express.static(path.join(__dirname,"public")));const rooms={};
const code=()=>Math.random().toString(36).slice(2,6).toUpperCase();
const pools={food:["🍔","🍟","🍕","🌮","🍩","🍓","🍉","🍪","🍿","🥨","🧁","🍦","🥞","🥑","🍒","🥝","🍇","🍎"],emojis:["😂","😍","😎","🤩","🥳","😜","🤯","😭","😡","🤔","😴","🤑","🤠","🥰","😈","🤓","🙃","😇"],animals:["🐶","🐱","🦁","🐯","🐼","🐵","🦊","🐸","🐨","🐰","🦄","🐷","🐮","🐙","🦋","🐢","🦜","🐬"],music:["🎵","🎧","🎤","🎹","🥁","🎷","🎺","🎸","🪩","📻","🎼","🎶","🕺","💿","🔊","🎻","🪕","🎚️"],movies:["🎬","🍿","🎟️","🎞️","📽️","⭐","🏆","🎭","👽","🦸","🧙","🤠","👑","🚀","🏰","🕵️","🧟","🦖"],slang:["BET","CAP","FIRE","VIBE","GOAT","TEA","SALTY","FLEX","SLAY","LIT","MOOD","DRIP","EXTRA","LOWKEY","HIGHKEY","ATE","PERIOD","SIS"],culture:["✊🏾","👑","🪮","🎤","🎶","📚","🎨","💃🏾","🕺🏾","🥁","🎓","💈","🍽️","🏆","❤️","✨","🖤","🤎"],inspiration:["FAITH","HOPE","LOVE","GRACE","JOY","PEACE","DREAM","GROW","SHINE","RISE","FOCUS","BELIEVE","PURPOSE","COURAGE","CREATE","THRIVE","BLOOM","WIN"],colors:["🔴","🟠","🟡","🟢","🔵","🟣","🟤","⚫","⚪","🩷","🩵","💚","💛","💜","❤️","🧡","💙","🤍"]};
function sh(a){a=[...a];for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function deck(cat,n){let v=sh(pools[cat]||pools.emojis).slice(0,n/2);return sh(v.flatMap((x,i)=>[{id:i+"a",pair:i,value:x,matched:false},{id:i+"b",pair:i,value:x,matched:false}]))}
function pub(r){return {...r,players:r.players.map(p=>({...p})),deck:r.deck.map(c=>({...c,value:(c.matched||r.status==="preview")?c.value:null}))}}
function emit(r){io.to(r.code).emit("state",pub(r))}
io.on("connection",s=>{
s.on("create",(o,cb)=>{let c;do c=code();while(rooms[c]);let n=Math.max(8,Math.min(36,+o.count||16));if(n%2)n++;rooms[c]={code:c,host:s.id,mode:o.mode||"classic",category:o.category||"food",count:n,status:"lobby",turn:0,players:[{id:s.id,name:String(o.name||"Host").slice(0,24),score:0}],deck:[],winner:null,previewUntil:0};s.join(c);cb({ok:true,code:c});emit(rooms[c])});
s.on("join",(o,cb)=>{let c=String(o.code||"").toUpperCase(),r=rooms[c];if(!r)return cb({ok:false,msg:"Room not found"});if(r.status!=="lobby")return cb({ok:false,msg:"Game already started"});r.players.push({id:s.id,name:String(o.name||"Player").slice(0,24),score:0});s.join(c);cb({ok:true,code:c});emit(r)});
s.on("start",c=>{let r=rooms[c];if(!r||r.host!==s.id)return;r.deck=deck(r.category,r.count);r.players.forEach(p=>p.score=0);r.turn=0;r.winner=null;if(r.mode==="flash"){let ms=Math.min(15000,4000+r.count*250);r.status="preview";r.previewUntil=Date.now()+ms;emit(r);setTimeout(()=>{if(rooms[c]===r&&r.status==="preview"){r.status="playing";emit(r)}},ms)}else{r.status="playing";emit(r)}});
s.on("flip",(o,cb)=>{let r=rooms[o.code];if(!r||r.status!=="playing")return cb&&cb({ok:false});let pi=r.players.findIndex(p=>p.id===s.id);if(pi<0||(r.mode==="turn"&&pi!==r.turn))return cb&&cb({ok:false,msg:"Not your turn"});let c=r.deck.find(x=>x.id===o.id);if(!c||c.matched)return cb&&cb({ok:false});cb&&cb({ok:true,value:c.value,pair:c.pair})});
s.on("pair",(o,cb)=>{let r=rooms[o.code];if(!r)return;let a=r.deck.find(x=>x.id===o.ids?.[0]),b=r.deck.find(x=>x.id===o.ids?.[1]),p=r.players.find(x=>x.id===s.id);if(!a||!b||!p||a.matched||b.matched)return;if(a.pair===b.pair){a.matched=b.matched=true;p.score++;if(r.deck.every(x=>x.matched)){r.status="finished";r.winner=[...r.players].sort((x,y)=>y.score-x.score)[0]}cb&&cb({match:true});emit(r)}else{if(r.mode==="turn")r.turn=(r.turn+1)%r.players.length;cb&&cb({match:false});emit(r)}});
s.on("disconnect",()=>{Object.keys(rooms).forEach(c=>{let r=rooms[c],i=r.players.findIndex(p=>p.id===s.id);if(i<0)return;r.players.splice(i,1);if(!r.players.length)return delete rooms[c];if(r.host===s.id)r.host=r.players[0].id;emit(r)})})
});server.listen(process.env.PORT||3000,()=>console.log("SWIS Memory Match running"));