const express=require("express"),http=require("http"),{Server}=require("socket.io"),path=require("path");
const app=express(),server=http.createServer(app),io=new Server(server);app.use(express.static(path.join(__dirname,"public")));const rooms={};
const code=()=>Math.random().toString(36).slice(2,6).toUpperCase();
const pools={money:["💎","🍀","🎲","🎯","🔥","⭐","👑","🚀","🎁","🏆","🍔","🎵","🎬","🐶","🌴","⚡","🎮","🎤","🪩","🍿","🦋","🌈","🏀","⚽","🎨","❤️","😎","🥳","🌟","🧠","🕶️"],food:["🍔","🍟","🍕","🌮","🍩","🍓","🍉","🍪","🍿","🥨","🧁","🍦","🥞","🥑","🍒","🥝","🍇","🍎"],emojis:["😂","😍","😎","🤩","🥳","😜","🤯","😭","😡","🤔","😴","🤑","🤠","🥰","😈","🤓","🙃","😇"],animals:["🐶","🐱","🦁","🐯","🐼","🐵","🦊","🐸","🐨","🐰","🦄","🐷","🐮","🐙","🦋","🐢","🦜","🐬"],music:["🎵","🎧","🎤","🎹","🥁","🎷","🎺","🎸","🪩","📻","🎼","🎶","🕺","💿","🔊","🎻","🪕","🎚️"],movies:["FRIDAY","COMING TO AMERICA","LOVE & BASKETBALL","THE WOOD","DREAMGIRLS","THE COLOR PURPLE","BLACK PANTHER","HOUSE PARTY","SOUL FOOD","BOOMERANG","THE BEST MAN","SET IT OFF","WAITING TO EXHALE","COOLEY HIGH","LEAN ON ME","JUICE","ATL","CREED"],slang:["BET","CAP","FIRE","VIBE","GOAT","TEA","SALTY","FLEX","SLAY","LIT","MOOD","DRIP","EXTRA","LOWKEY","HIGHKEY","ATE","PERIOD","SIS"],culture:["✊🏾","👑","🪮","🎤","🎶","📚","🎨","💃🏾","🕺🏾","🥁","🎓","💈","🍽️","🏆","❤️","✨","🖤","🤎"],inspiration:["FAITH","HOPE","LOVE","GRACE","JOY","PEACE","DREAM","GROW","SHINE","RISE","FOCUS","BELIEVE","PURPOSE","COURAGE","CREATE","THRIVE","BLOOM","WIN"],colors:["COLOR:#ef4444|RED","COLOR:#f97316|ORANGE","COLOR:#facc15|YELLOW","COLOR:#22c55e|GREEN","COLOR:#3b82f6|BLUE","COLOR:#a855f7|PURPLE","COLOR:#92400e|BROWN","COLOR:#111827|BLACK","COLOR:#f8fafc|WHITE","COLOR:#ec4899|PINK","COLOR:#06b6d4|CYAN","COLOR:#84cc16|LIME","COLOR:#14b8a6|TEAL","COLOR:#6366f1|INDIGO","COLOR:#f43f5e|ROSE","COLOR:#d946ef|MAGENTA","COLOR:#64748b|SLATE","COLOR:#f59e0b|GOLD"]};
function sh(a){a=[...a];for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function deck(cat,n){
 if(cat==="money"){let pics=sh(pools.money);let a=Array.from({length:31},(_,i)=>({id:"m"+i,pair:-1,value:pics[i%pics.length],matched:false,eliminated:false,money:false}));a.push({id:"money",pair:999,value:"$$",matched:false,eliminated:false,money:true});a=sh(a);a.forEach((c,i)=>c.number=i+1);return a}
 let v=sh(pools[cat]||pools.emojis).slice(0,n/2);return sh(v.flatMap((x,i)=>[{id:i+"a",pair:i,value:x,matched:false},{id:i+"b",pair:i,value:x,matched:false}]))
}
function pub(r){return {...r,moneyNumber:r.status==="finished"?r.moneyNumber:null,mediaReady:undefined,players:r.players.map(p=>({...p})),moneyPicks:[...(r.moneyPicks||[])],deck:r.deck.map(c=>({...c,value:(c.matched||c.eliminated||r.status==="preview")?c.value:null,money:(c.eliminated||c.matched)?!!c.money:false}))}}
function emit(r){io.to(r.code).emit("state",pub(r))}
function finish(r,winner=null){r.status="finished";r.elapsedSeconds=Math.max(0,Math.floor((Date.now()-(r.startedAt||Date.now()))/1000));r.winner=winner||[...r.players].sort((a,b)=>b.score-a.score)[0]||null;emit(r)}
function resetRound(r){r.deck=[];r.turn=0;r.winner=null;r.previewUntil=0;r.startedAt=0;r.elapsedSeconds=0;r.moneyPicks=[];r.moneyNumber=null;r.revealStarted=false;r.players.forEach(p=>{p.score=0;p.moneyPick=null;p.lockedNumbers=[]});r.status="lobby"}
io.on("connection",s=>{
 s.on("create",(o,cb)=>{let c;do c=code();while(rooms[c]);let n=o.mode==="money"?32:Math.max(8,Math.min(36,+o.count||16));if(n%2)n++;let r=rooms[c]={code:c,host:s.id,mode:o.mode||"classic",category:o.mode==="money"?"money":(o.category||"food"),count:n,status:"lobby",turn:0,players:[{id:s.id,name:String(o.name||"Host").slice(0,24),score:0,moneyPick:null,lockedNumbers:[]}],deck:[],winner:null,previewUntil:0,startedAt:0,elapsedSeconds:0,moneyPicks:[],moneyNumber:null,revealStarted:false,mediaReady:new Set()};s.join(c);cb({ok:true,code:c});emit(r)});
 s.on("join",(o,cb)=>{let c=String(o.code||"").trim().toUpperCase(),r=rooms[c];if(!r)return cb({ok:false,msg:"Room not found. Check the code and try again."});if(r.status!=="lobby")return cb({ok:false,msg:"That game has already started."});let max=r.mode==="money"?32:20;if(r.players.length>=max)return cb({ok:false,msg:`This room is full (${max} players).`});if(!r.players.some(p=>p.id===s.id))r.players.push({id:s.id,name:String(o.name||"Player").slice(0,24),score:0,moneyPick:null,lockedNumbers:[]});s.join(c);cb({ok:true,code:c,mode:r.mode,category:r.category,count:r.count});emit(r)});
 s.on("reconfigure-room",(o,cb)=>{let r=rooms[o.code];if(!r)return cb&&cb({ok:false,msg:"Room not found."});if(r.host!==s.id)return cb&&cb({ok:false,msg:"Only the host can change the next round."});let allowed=["classic","flash","speed","turn","money"],mode=allowed.includes(o.mode)?o.mode:"classic",count=mode==="money"?32:Math.max(8,Math.min(36,+o.count||16));if(count%2)count++;r.mode=mode;r.category=mode==="money"?"money":(pools[o.category]?o.category:"food");r.count=count;resetRound(r);emit(r);cb&&cb({ok:true})});
 s.on("start",(c,cb)=>{let r=rooms[c];if(!r)return cb&&cb({ok:false,msg:"Room not found."});if(r.host!==s.id)return cb&&cb({ok:false,msg:"Only the host can start the game."});if(r.mode==="money"&&!r.players.every(p=>(p.lockedNumbers||[]).length))return cb&&cb({ok:false,msg:"Every player must lock in at least one number first."});r.deck=deck(r.mode==="money"?"money":r.category,r.count);r.players.forEach(p=>{p.score=0;p.moneyPick=null});r.moneyPicks=[];r.turn=0;r.winner=null;r.startedAt=Date.now();r.elapsedSeconds=0;if(r.mode==="flash"){let ms=Math.min(15000,4000+r.count*250);r.status="preview";r.previewUntil=Date.now()+ms;emit(r);setTimeout(()=>{if(rooms[c]===r&&r.status==="preview"){r.status="playing";emit(r)}},ms)}else{r.status="playing";emit(r)}cb&&cb({ok:true})});
 s.on("restart-room",c=>{let r=rooms[c];if(!r||r.host!==s.id)return;resetRound(r);emit(r)});
 s.on("leave-room",c=>{let r=rooms[c];if(!r)return;let i=r.players.findIndex(p=>p.id===s.id);if(i<0)return;r.players.splice(i,1);r.mediaReady.delete(s.id);s.leave(c);s.to(c).emit("media-left",{id:s.id});if(!r.players.length){delete rooms[c];return}if(r.host===s.id)r.host=r.players[0].id;emit(r)});
 s.on("lock-money-numbers",(o,cb)=>{let r=rooms[o.code];if(!r||r.mode!=="money"||r.status!=="lobby")return cb&&cb({ok:false,msg:"Money picks are closed."});let p=r.players.find(x=>x.id===s.id);if(!p)return cb&&cb({ok:false,msg:"You are not in this room."});if((p.lockedNumbers||[]).length)return cb&&cb({ok:false,msg:"Your numbers are already locked."});let nums=[...new Set((o.numbers||[]).map(Number).filter(n=>n>=1&&n<=32))].sort((a,b)=>a-b);if(!nums.length)return cb&&cb({ok:false,msg:"Choose at least one number."});let taken=new Set(r.players.flatMap(x=>x.id===s.id?[]:(x.lockedNumbers||[])));let conflict=nums.find(n=>taken.has(n));if(conflict)return cb&&cb({ok:false,msg:`#${conflict} is already locked by another player.`});p.lockedNumbers=nums;cb&&cb({ok:true});emit(r)});
 s.on("begin-money-reveal",c=>{let r=rooms[c];if(!r||r.host!==s.id||r.mode!=="money"||r.status!=="playing"||r.revealStarted)return;r.revealStarted=true;let order=sh(r.deck.map(x=>x.number)),moneyCard=r.deck.find(x=>x.money);r.moneyNumber=moneyCard.number;let i=0;function next(){if(!rooms[c]||rooms[c]!==r||r.status!=="playing")return;if(i>=order.length)return;let n=order[i++],card=r.deck.find(x=>x.number===n);card.eliminated=true;let owner=r.players.find(p=>(p.lockedNumbers||[]).includes(n));io.to(c).emit("money-reveal",{number:n,value:card.value,money:card.money,winnerName:card.money?(owner?.name||"NO WINNER"):null});emit(r);if(card.money){if(owner){owner.score=1;return setTimeout(()=>finish(r,owner),1900)}else{return setTimeout(()=>finish(r,null),1900)}}setTimeout(next,1150)}setTimeout(next,700)});
 s.on("flip",(o,cb)=>{let r=rooms[o.code];if(!r||r.status!=="playing"||r.mode==="money")return cb&&cb({ok:false});let pi=r.players.findIndex(p=>p.id===s.id);if(pi<0||(r.mode==="turn"&&pi!==r.turn))return cb&&cb({ok:false,msg:"Not your turn"});let c=r.deck.find(x=>x.id===o.id);if(!c||c.matched)return cb&&cb({ok:false});cb&&cb({ok:true,value:c.value,pair:c.pair,money:false})});
 s.on("pair",(o,cb)=>{let r=rooms[o.code];if(!r||r.status!=="playing"||r.mode==="money")return;let a=r.deck.find(x=>x.id===o.ids?.[0]),b=r.deck.find(x=>x.id===o.ids?.[1]),p=r.players.find(x=>x.id===s.id);if(!a||!b||!p||a.matched||b.matched)return;if(a.pair===b.pair){a.matched=b.matched=true;p.score++;cb&&cb({match:true});if(r.deck.every(x=>x.matched))return finish(r);emit(r)}else{if(r.mode==="turn")r.turn=(r.turn+1)%r.players.length;cb&&cb({match:false});emit(r)}});
 s.on("money-pick",(o,cb)=>{let r=rooms[o.code];if(!r||r.status!=="playing"||r.mode!=="money")return cb&&cb({ok:false,msg:"Money round is not active."});let p=r.players.find(x=>x.id===s.id);if(!p)return cb&&cb({ok:false,msg:"You are not in this room."});let c=r.deck.find(x=>x.id===o.id);if(!c||c.eliminated)return cb&&cb({ok:false,msg:"That number has already been chosen."});c.eliminated=true;p.moneyPick={number:c.number,money:!!c.money};let pick={id:p.id,name:p.name,number:c.number,money:!!c.money,cardId:c.id};r.moneyPicks.push(pick);cb&&cb({ok:true,money:!!c.money,number:c.number});if(c.money){p.score=1;io.to(r.code).emit("money-winner",{id:p.id,name:p.name,number:c.number,cardId:c.id});return finish(r,p)}let lines=["Sorry","Maybe Next Time","Awwww","Nice Try"],line=lines[Math.floor(Math.random()*lines.length)];io.to(r.code).emit("money-miss",{id:p.id,name:p.name,number:c.number,cardId:c.id,line});emit(r);if(r.players.every(x=>x.moneyPick)&&!r.winner){/* all current players picked; host may replay same room */}});
 s.on("room-chat",o=>{let r=rooms[o.code];if(!r)return;let p=r.players.find(x=>x.id===s.id);if(!p)return;let text=String(o.text||"").trim().slice(0,180);if(!text)return;io.to(r.code).emit("room-chat",{id:s.id,name:p.name,text})});
 s.on("media-ready",o=>{let r=rooms[o.code];if(!r||!r.players.some(p=>p.id===s.id))return;r.mediaReady.add(s.id);let ids=[...r.mediaReady].filter(id=>r.players.some(p=>p.id===id));io.to(s.id).emit("media-roster",{ids});for(const id of ids){if(id===s.id)continue;let initiator=s.id<id;io.to(s.id).emit("media-peer",{id,initiator});io.to(id).emit("media-peer",{id:s.id,initiator:!initiator})}});
 s.on("webrtc-offer",o=>{let r=rooms[o.code];if(r&&r.players.some(p=>p.id===s.id)&&r.players.some(p=>p.id===o.to))io.to(o.to).emit("webrtc-offer",{from:s.id,description:o.description})});
 s.on("webrtc-answer",o=>{let r=rooms[o.code];if(r&&r.players.some(p=>p.id===s.id)&&r.players.some(p=>p.id===o.to))io.to(o.to).emit("webrtc-answer",{from:s.id,description:o.description})});
 s.on("webrtc-ice",o=>{let r=rooms[o.code];if(r&&r.players.some(p=>p.id===s.id)&&r.players.some(p=>p.id===o.to))io.to(o.to).emit("webrtc-ice",{from:s.id,candidate:o.candidate})});
 s.on("disconnect",()=>{Object.keys(rooms).forEach(c=>{let r=rooms[c],i=r.players.findIndex(p=>p.id===s.id);if(i<0)return;r.mediaReady.delete(s.id);s.to(c).emit("media-left",{id:s.id});r.players.splice(i,1);if(!r.players.length){delete rooms[c];return}if(r.host===s.id)r.host=r.players[0].id;if(r.turn>=r.players.length)r.turn=0;emit(r)})})
});
server.listen(process.env.PORT||3000,()=>console.log("SWIS Memory Match v7 running"));
